# .gitlab-ci.yml файл расположен в корневом каталоге репозитория

  image: node:latest
  stages:
    - build
    - deploy
  
  build:
    stage: build
    script:
      - npm install
      - npm run-script build

  deploy:
    stage: deploy
    script:
      - npm run-script deploy
